server:
  port: 8763
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #
spring:
  application:
    name: ribbon-client
  redis:
    database: 0
    password: 1234
    host: 39.105.37.199
    port: 6379
    timeout: 50000
