server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false # 是否启用自我保护机制，官方推荐开发模式下开启，生产模式下关闭
    eviction-interval-timer-in-ms: 50000 #  每5秒钟对分区故障节点进行剔除
  client:
    registerWithEureka: false # 是否向注册中心server进行注册
    fetchRegistry: false # 是否获取注册中心列表
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #http://localhost:8761/abc/ 注册中信息


    # 定义注册中名字
spring:
  application:
    name: eureka-server
  redis:
    database: 0
    password: 1234
    host: 39.105.37.199
    port: 6379
    timeout: 50000
