server:
  port: 8770
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: zuul-client
  redis:
    port: 6379
    host: 39.105.37.199
    password: 1234
    database: 0
    timeout: 50000
zuul:
  ignoredServices: "*"
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    8762:
      path: /8762/**
      service-id: feign-client
      sensitiveHeaders: "*"
    8763:
      path: /8763/**
      service-id: ribbon-client
      sensitiveHeaders: "*"
